$ErrorActionPreference = 'Stop'

$projectRoot = Split-Path -Parent $PSScriptRoot
$workspaceRoot = Split-Path -Parent $projectRoot
$sourcePath = Join-Path $projectRoot 'build\flutter_assets\NOTICES'
$archiveRoot = Join-Path $workspaceRoot 'release_legal'
$archivePath = Join-Path $archiveRoot 'THIRD_PARTY_NOTICES.txt'
$manifestPath = Join-Path $archiveRoot 'DEPENDENCY_LICENSE_MANIFEST.txt'

if (-not (Test-Path -LiteralPath $sourcePath)) {
  throw "Flutter dependency notices were not found at $sourcePath. Run a Flutter build first."
}

New-Item -ItemType Directory -Path $archiveRoot -Force | Out-Null
Copy-Item -LiteralPath $sourcePath -Destination $archivePath -Force

$hash = (Get-FileHash -LiteralPath $archivePath -Algorithm SHA256).Hash
$size = (Get-Item -LiteralPath $archivePath).Length
$manifest = @(
  'Pinball Neo 95 dependency license archive',
  '',
  'Archive file: release_legal/THIRD_PARTY_NOTICES.txt',
  'Source file: game_app/build/flutter_assets/NOTICES',
  "Archive size: $size bytes",
  "SHA-256: $hash",
  '',
  'This report is generated by game_app/tool/archive_dependency_notices.ps1.',
  'Regenerate it after every release build so it matches the shipped Flutter asset bundle.'
)
Set-Content -LiteralPath $manifestPath -Value $manifest -Encoding utf8

Write-Output "Archived Flutter dependency notices: $archivePath ($size bytes)."
